### ISSUE TITLE
Thank you for this!

### ISSUE THREAD

**Issue by Download** [queckezz/watch-run#11]
Thank you for this great work!

It actually inspired two derivative projects:

* [wait-run](https://npmjs.org/package/wait-run)
* [just-wait](https://npmjs.org/package/just-wait)

I am mentioning you as a copyright holder on my fork `just-wait`.

Just one question:
You are licensing under MIT, @RickWong under BSD-3-clause and myself under Creative Commons.

Is it ok by you if I tell people they can take their pick from these three licenses?

**Comment by queckezz** [comment]
This is pretty awesome! I'm always happy to see better approaches. To be honest, this package is quite outdated. I'll recommend your package here since it's much better. 

> Is it ok by you if I tell people they can take their pick from these three licenses?

Sure, I'm fine with that.

**Comment by queckezz** [comment]
d69fbbee6fe9303fbe1d505494aaee7c2da49070

**Comment by Download** [comment]
Thank you!  :+1:
