### ISSUE TITLE
Error: watch null EPERM

### ISSUE THREAD

**Issue by entrptaher** [queckezz/watch-run#12]
If I use this pattern, create and remove a directory without making any files inside it, then the process hangs and closes.
```
watch-run -p '*' echo "File Changed"
```
then, on another terminal
```
mkdir Test
rmdir Test
```
back to previous terminal, and 
```

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: watch null EPERM
    at exports._errnoException (util.js:870:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1217:21)
```

**Comment by queckezz** [comment]
Hey man, thanks for trying this module out. However, this is quite outdated and I stated in the readme that there are successors to it. They might already have fixed your issue. See

* https://github.com/RickWong/wait-run
* https://github.com/Qard/onchange
* https://github.com/download/just-wait
