### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by axelpale** [queckezz/watch-run#13]
NPM gives the following annoying warnings when `watch-run` is installed. I am sorry to say this but this caused me to give `npm-watch` another shot even though `watch-run` was more like what I was looking for.

    xeli-air:taach xeli$ npm install watch-run -g
    npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
    npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
    /usr/local/bin/watch-run -> /usr/local/lib/node_modules/watch-run/bin/watch
    /usr/local/lib
    └─┬ watch-run@1.2.4 
      ├── commander@2.1.0 
      ├── debug@0.7.4 
      └─┬ gaze@0.4.3 
        └─┬ globule@0.1.0 
          ├─┬ glob@3.1.21 
          │ ├── graceful-fs@1.2.3 
          │ └── inherits@1.0.2 
          ├── lodash@1.0.2 
          └─┬ minimatch@0.2.14 
            ├── lru-cache@2.7.3 
            └── sigmund@1.0.1

**Comment by axelpale** [comment]
A tool `npm-check-updates` can help you in the upgrade process.

    $ npm install -g npm-check-updates
    $ ncu  # to view available upgrades
    $ ncu  # to upgrade

**Comment by queckezz** [comment]
Hey man, thanks for trying this module out. However, this is quite outdated and I stated in the readme that there are successors to it. They probably have updated their dependencies. See

https://github.com/RickWong/wait-run
https://github.com/Qard/onchange
https://github.com/download/just-wait

**Comment by axelpale** [comment]
Thanks for the info. Somehow I missed the deprecation notes although they are obvious when looking at the readme now.
