### ISSUE TITLE
Windows style line endings result with error

### ISSUE THREAD

**Issue by tadatuta** [queckezz/watch-run#5]
Version `1.1.0` published in `npm` results with

```sh
watch-run$ ./bin/watch
env: node\r: No such file or directory
```
at least on macOS.

That's because of Windows style line endins.

**Comment by voischev** [comment]
+1

**Comment by ahdinosaur** [comment]
+1

a workaround is to use the GitHub repo as your package source with `npm i --save queckezz/watch-run`.

**Comment by queckezz** [comment]
I tried a bunch of different things (dos2unix, git config, git attributes) and bumped the package to `1.2.1`. Hopefully it works now!
