### ISSUE TITLE
Multiple patterns to watch

### ISSUE THREAD

**Issue by parshap** [queckezz/watch-run#9]
I'd ike to supply multiple patterns to watch. I've tried the following two ways, but neither work.

```
$ run watch -p 'index.js lib/*.js' -- echo hello
```

```
$ run watch -p index.js -p 'lib/*.js' -- echo hello
```

`gaze` supports being given an array of patterns, but it looks like `commander` can't parse multiple `-p` arguments.

**Comment by voischev** [comment]
:+1:

**Comment by commenthol** [comment]
@queckezz can you please publish the last changes to npm? Thanks a lot.

**Comment by queckezz** [comment]
Published! Also gave you publishing rights.

**Comment by commenthol** [comment]
Cool thanks
